[2023-12-05T19:46:48.091+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.insert_into_db manual__2023-12-05T19:41:43.530100+00:00 [queued]>
[2023-12-05T19:46:48.096+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.insert_into_db manual__2023-12-05T19:41:43.530100+00:00 [queued]>
[2023-12-05T19:46:48.097+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-05T19:46:48.104+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_into_db> on 2023-12-05 19:41:43.530100+00:00
[2023-12-05T19:46:48.108+0000] {standard_task_runner.py:57} INFO - Started process 2529 to run task
[2023-12-05T19:46:48.111+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'insert_into_db', 'manual__2023-12-05T19:41:43.530100+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_extract.py', '--cfg-path', '/tmp/tmphj2l0fgu']
[2023-12-05T19:46:48.113+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask insert_into_db
[2023-12-05T19:46:48.148+0000] {task_command.py:416} INFO - Running <TaskInstance: extract_dag.insert_into_db manual__2023-12-05T19:41:43.530100+00:00 [running]> on host d4f23c87a93c
[2023-12-05T19:46:48.196+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='insert_into_db' AIRFLOW_CTX_EXECUTION_DATE='2023-12-05T19:41:43.530100+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-05T19:41:43.530100+00:00'
[2023-12-05T19:46:48.201+0000] {utils.py:76} INFO - Conectándose a la base de datos...
[2023-12-05T19:46:48.202+0000] {utils.py:81} INFO - Conexión a la base de datos establecida exitosamente
[2023-12-05T19:46:48.203+0000] {logging_mixin.py:154} INFO - Error fetching pairs: string indices must be integers
[2023-12-05T19:46:48.204+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/main.py", line 49, in insert_into_db
    df_trades = generate_df_trades(df, whitelist=whitelist)
  File "/opt/airflow/scripts/main.py", line 30, in generate_df_trades
    df = df_original.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
[2023-12-05T19:46:48.212+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=insert_into_db, execution_date=20231205T194143, start_date=20231205T194648, end_date=20231205T194648
[2023-12-05T19:46:48.219+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task insert_into_db ('NoneType' object has no attribute 'copy'; 2529)
[2023-12-05T19:46:48.243+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-05T19:46:48.257+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
