[2023-12-05T19:41:47.578+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.insert_into_db manual__2023-12-05T19:41:43.530100+00:00 [queued]>
[2023-12-05T19:41:47.583+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.insert_into_db manual__2023-12-05T19:41:43.530100+00:00 [queued]>
[2023-12-05T19:41:47.584+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-05T19:41:47.591+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_into_db> on 2023-12-05 19:41:43.530100+00:00
[2023-12-05T19:41:47.594+0000] {standard_task_runner.py:57} INFO - Started process 2358 to run task
[2023-12-05T19:41:47.597+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'insert_into_db', 'manual__2023-12-05T19:41:43.530100+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_extract.py', '--cfg-path', '/tmp/tmppf94wk9j']
[2023-12-05T19:41:47.599+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask insert_into_db
[2023-12-05T19:41:47.631+0000] {task_command.py:416} INFO - Running <TaskInstance: extract_dag.insert_into_db manual__2023-12-05T19:41:43.530100+00:00 [running]> on host d4f23c87a93c
[2023-12-05T19:41:47.679+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='insert_into_db' AIRFLOW_CTX_EXECUTION_DATE='2023-12-05T19:41:43.530100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-05T19:41:43.530100+00:00'
[2023-12-05T19:41:47.685+0000] {utils.py:76} INFO - Conectándose a la base de datos...
[2023-12-05T19:41:47.686+0000] {utils.py:81} INFO - Conexión a la base de datos establecida exitosamente
[2023-12-05T19:41:47.687+0000] {logging_mixin.py:154} INFO - Error fetching pairs: string indices must be integers
[2023-12-05T19:41:47.687+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/main.py", line 49, in insert_into_db
    df_trades = generate_df_trades(df)
TypeError: generate_df_trades() missing 1 required positional argument: 'whitelist'
[2023-12-05T19:41:47.695+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=insert_into_db, execution_date=20231205T194143, start_date=20231205T194147, end_date=20231205T194147
[2023-12-05T19:41:47.702+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task insert_into_db (generate_df_trades() missing 1 required positional argument: 'whitelist'; 2358)
[2023-12-05T19:41:47.731+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-05T19:41:47.746+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
